import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

live_config_reload = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9
dynamic_title = true
dynamic_padding = true

[window.padding]
x = 5
y = 5

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 10
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[env]
TERM = "xterm-256color"
